"""empty message

Revision ID: 668680ab2b29
Revises: 
Create Date: 2021-11-05 10:18:37.213791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668680ab2b29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('order', sa.String(length=50), nullable=True))
    op.drop_column('pokemon', 'base_xp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('base_xp', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('pokemon', 'order')
    # ### end Alembic commands ###
