"""empty message

Revision ID: 691b0612b8c7
Revises: 668680ab2b29
Create Date: 2021-11-05 10:30:46.827787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691b0612b8c7'
down_revision = '668680ab2b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('poke_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'poke_id')
    # ### end Alembic commands ###
