"""empty message

Revision ID: e362586d86ee
Revises: 691b0612b8c7
Create Date: 2021-11-09 07:47:44.239391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e362586d86ee'
down_revision = '691b0612b8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('won', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('lost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lost')
    op.drop_column('user', 'won')
    # ### end Alembic commands ###
